baseURL = "https://dennislee.xyz/"
languageCode = "en-us"
title = "Dennis Lee"
theme = "hugo-ivy"
footnotereturnlinkcontents = "â†©"
enableGitInfo = true
enableRobotsTXT = true
copyright = """
This page is licensed under a [Creative Commons Attribution 4.0 International License][CC-BY-4.0].

   [![CC-BY-4.0](https://mirrors.creativecommons.org/presskit/buttons/88x31/svg/by.svg)][CC-BY-4.0]

   [CC-BY-4.0]: https://creativecommons.org/licenses/by/4.0/
"""

[permalinks]
	blog = "/:year/:slug/"

# [[menu.main]]
# 	name= "Blog"
# 	url= "/blog"
[[menu.main]]
	name = "Email"
	pre = "ðŸ“§"
	url = "mailto:%64%65%6E%6E%69%73%40%64%65%6E%6E%69%73%6C%65%65%2E%78%79%7A"
[[menu.main]]
	name = "GitHub"
	pre = '<img src="https://github.githubassets.com/favicons/favicon.svg" width="16" height="16">'
	url = "https://github.com/dennisleexyz"
[[menu.main]]
	name = "GitLab"
	pre = '<img src="https://gitlab.com/assets/favicon-7901bd695fb93edb07975966062049829afb56cf11511236e61bcf425070e36e.png" width="16" height="16">'
	url = "https://gitlab.com/dennisleexyz"
# [[menu.main]]
# 	name= "RÃ©sumÃ©/CV"
# 	url= ""
[[menu.main]]
	name = "subscribe via RSS"
	pre = '<img src="https://upload.wikimedia.org/wikipedia/en/4/43/Feed-icon.svg" width="16" height="16">'
	url = "/index.xml"

# [params]
# 	description = ""

[taxonomies]

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true
