baseURL = "https://dennislee.xyz/"
languageCode = "en-us"
title = "Dennis Lee"
theme = "hugo-ivy"
footnotereturnlinkcontents = "↩"
enableGitInfo = true
enableRobotsTXT = true
copyright = """
This page is licensed under a [Creative Commons Attribution 4.0 International License][CC-BY-4.0].

   [![CC-BY-4.0](https://mirrors.creativecommons.org/presskit/buttons/88x31/svg/by.svg)][CC-BY-4.0]

   [CC-BY-4.0]: https://creativecommons.org/licenses/by/4.0/
"""

[permalinks]
	blog = "/:year/:slug/"

# [[menu.main]]
# 	name= "Blog"
# 	url= "/blog"
[[menu.main]]
	name = "Email"
	pre = '<span class="fas fa-envelope"></span> '
	url = "mailto:%44%65%6E%6E%69%73%40%44%65%6E%6E%69%73%4C%65%65%2E%78%79%7A"
[[menu.main]]
	name = "GitHub"
	pre = '<span class="fab fa-github"></span> '
	url = "https://github.com/DennisLeexyz"
[[menu.main]]
	name = "GitLab"
	pre = '<span class="fab fa-gitlab"></span> '
	url = "https://gitlab.com/DennisLeexyz"
[[menu.main]]
	name= "Projects"
	pre = '<span class="fa fa-project-diagram"></span> '
	url= "/projects"
# [[menu.main]]
# 	name= "Résumé/CV"
# 	url= ""
[[menu.main]]
	name= "Setup"
	pre = '<span class="fa fa-desktop"></span> '
	url= "https://github.com/dennisleexyz/dotfiles/wiki"
[[menu.main]]
	name = "Subscribe"
	pre = '<span class="fa fa-rss"></span> '
	url = "/index.xml"
# [[menu.main]]
# 	name = "Twitter"
# 	pre = '<span class="fab fa-twitter"></span> '
# 	url = "https://twitter.com/DennisLeexyz"

# [params]
# 	description = ""

[taxonomies]

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true
